version: '3.6'

services:
  srvdb:
    image: postgres
    container_name: srvdb
    hostname: srvdb
    environment:
      POSTGRES_USER: consultas
      POSTGRES_DB: consultas
      POSTGRES_PASSWORD: QueryConSql.pwd
      TZ:  America/Guayaquil
    ports:
      - 5432:5432
    networks:
      - datalogger_net
    volumes:
      - pg_data2:/var/lib/postgresql/data


  srvwildfly:
    image: ups/demoappdocker
    container_name: srvwildfly
    hostname: srvwildfly
    environment:
      TZ:  America/Guayaquil
    ports:
      - 8082:8080
      - 8899:8009
      - 9992:9990
      - 8787:8787
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -c standalone.xml -bmanagement 0.0.0.0 --debug *:8787
    depends_on:
      - srvdb
    networks:
      - datalogger_net

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy-demo
    depends_on:
     - srvwildfly    
     - srvdb  
    volumes:
       - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
         - "80:80"
    networks:
      - datalogger_net
      
    restart: always
      
      
volumes:
  pg_data2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/Portal Center/Documents/datapg

networks:
  datalogger_net:
  
  
  
 